### ISSUE TITLE
Format on save is not working on 4.2.1

### ISSUE THREAD

**Issue by LaurentOngaro** [Daylily-Zeleen/GDScript-Formatter#2]
If "Format on save" is enabled in the preferences, the code is not formatted on save and the following message "Format on save failed: due to engine bug. Please report an issue." is displayed in the output window.

Tested on Godot  4.2.1 standard version.

Note that the ["Format on Save" plugin](https://github.com/ryannhg/gdformat-on-save) work well (no issue), and it can be used in replacement of the same feature of this plugin.

**Comment by Daylily-Zeleen** [comment]
Are your using external editor?

**Comment by LaurentOngaro** [comment]
VScode is configured as an external editor but I'm using the godot script editor in that case

**Comment by Daylily-Zeleen** [comment]
Already do some change for this.
It will format anyway when saving a script. But it may not reload the code editor.
I am not sure that how to reproduce your issue, so please test and tell me the result.

**Comment by LaurentOngaro** [comment]
The issue has gone with the latest version on this repo.
But still exists with the version on the AssetLib.
Thanks for your work
