### ISSUE TITLE
Please distribute LICENSE file

### ISSUE THREAD

**Issue by HotariTobu** [Daylily-Zeleen/GDScript-Formatter#8]
Thank you for publishing the addon!

The addon is under MIT license so users have to include the license statements in their repos if they include the addon contents in the repos.
For users to skip copying `LICENSE.txt` to their repos manually, I like you to distribute the file with addon scripts.

**Comment by Daylily-Zeleen** [comment]
Thanks for your advise!
Already add by this [commit](https://github.com/Daylily-Zeleen/GDScript-Formatter/commit/d55e5e0057e65367979d588a12cfcd3fe76830fd).
